# Generated by Django 4.2.3 on 2023-09-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_customuser_email_varification_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email_varification_token',
            new_name='email_verification_token',
        ),
    ]
