# Generated by Django 4.2.3 on 2023-09-13 09:13

from django.db import migrations, models
import matrimony.models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='caste',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father',
            field=models.CharField(max_length=1000, null=True, verbose_name=matrimony.models.father_profile),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, default='Not specified', max_length=100, null=True),
        ),
    ]
